### ISSUE TITLE
 How to manage multiple authentications with different permissions per application

### ISSUE THREAD

**Issue by dimtitricognet** [Azure/EasyAuthForK8s#108]
Hello,

We have multiple applications that we need to deploy in AKS where we need to perform authentication to retrieve permissions from Azure AD / app registration in order to authenticate the user. My question is, do we need to deploy EasyAuthForK8s X times (one per app), or does the solution natively handle multi-authentication across multiple applications with different access rights?

Best Regards,
Dimitri

**Comment by karpikpl** [comment]
I think there's only one app registration that EasyAuth uses, but you can create different app roles for each of your use cases and require it on ingress level

**Comment by dimtitricognet** [comment]
thank you @karpikpl
