### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by eskaufel** [Azure/EasyAuthForK8s#23]
There has been no update for a while, and the documentation is half-finished.

**Comment by storesund** [comment]
I am curious about the same thing. I've made the project work in an AKS deployment, but only with interactive sign-in and cookies. The documentation seems to be outdated in regards to using EasyAuthForK8s for purely token-based applications. I eventually switched to using OAuth2Proxy instead, but would love for this project to be a real alternative.

**Comment by danielkon96** [comment]
The project was put on pause as the team was busy with their main jobs. We plan to work on it.
