### ISSUE TITLE
Is there an equivalent to the ".auth/me" endpoint?

### ISSUE THREAD

**Issue by ioeifcss** [Azure/EasyAuthForK8s#60]
With EasyAuth for PaaS Function/Web apps, one of the built-in endpoints you have access to is the `BASE_URL/.auth/me`.

_(where `BASE_URL` is something like `https://foo.azurewebsites.net`)_

This is quite useful when you're testing in your nonproduction environment and you need to get a real token out of AAD etc, similar to the example below:
![image](https://user-images.githubusercontent.com/93769471/147770493-d6b5ff8b-8d73-4f26-9a43-6659c4aa74bc.png)

Is there an equivalent within EasyAuthForK8s? The closest I could find was `BASE_URL/auth/me` which simply prints out my UPN and nothing else.

**Comment by jonlester** [comment]
We do not have that, or plans to implement it.  We do however have a feature upcoming that will allow you to specify a Microsoft graph query that will be executed on your behalf to populate the headers.  So getting data form something like https://graph.microsoft.com/beta/me would be possible.  Would that solve this for you?

**Comment by ioeifcss** [comment]
That may work, yeah. Is there a timeline for when this new feature will be out? I can see there has been activity on the `dev-dotnet6` branch which is promising

**Comment by jonlester** [comment]
It should be soon.  I'll defer to @danielkon96 for specifics

**Comment by danielkon96** [comment]
The `dev-dotnet6` branch should have work completed by the end of the month. After that, the plan is to merge all our changes into dev and then eventually into master around the same time.

**Comment by ioeifcss** [comment]
Brilliant stuff - looking forward to trying it out then!

**Comment by danielkon96** [comment]
@ioeifcss The latest changes have been pushed to master. Any feedback about the latest changes will be greatly appreciated!
