### ISSUE TITLE
Add End-to-End tests

### ISSUE THREAD

**Issue by kevinmgates** [Azure/EasyAuthForK8s#7]
Edit (Danielkon96): 
- Build and deploy docker image to existing environment (existing AAD Application and AKS cluster)
- Update automation helm values
- Replace kuard image with a custom built image that returns responses that the test can use. (For Jon: Dial tone environment)

- Get B2C well documented. See issue here: https://github.com/Azure/EasyAuthForK8s/issues/24

**Comment by danielkon96** [comment]
Update: look at Dapr/Tests for ideas
