### ISSUE TITLE
QuickStart Documentation Improvement

### ISSUE THREAD

**Issue by danielkon96** [Azure/EasyAuthForK8s#70]
The quick start does not make it clear exactly what will be installed and configured as part the installation. Maybe expand the quick start by outlining what will be installed and that you’ll be able to immediately try out requests against the example stub application.

**Comment by Whowong** [comment]
To expand on this, I think it could be helpful if a basic test to showcase and validate that it is working is provided.  The script also does take some time, a heads up on estimated runtime is also helpful to make sure im not wonding whats going on.
