### ISSUE TITLE
Infinite Loop Error running main.sh script in quickstart

### ISSUE THREAD

**Issue by Whowong** [Azure/EasyAuthForK8s#72]
While attempting to run the "Quickstart using Azure Cloud Shell" I receive the following error when running the main.sh bash script.  Here is the command I used:

bash main.sh -a easy-auth-demo -c ahcsaeasyauthfork8sp3 -r easy-authp3 -e email@contoso.com -l eastus

Error:

https://docs.microsoft.com/en-US/cli/azure/ad/app#az_ad_app_show
Read more about the command in reference docs
Polling status of AAD object creation for app....
ERROR: argument --id: expected one argument

Examples from AI knowledge base:
az ad app show --id 00000000-0000-0000-0000-000000000000
Get the details of an application. (autogenerated)

https://docs.microsoft.com/en-US/cli/azure/ad/app#az_ad_app_show
Read more about the command in reference docs
ERROR. INFINITE LOOP in 3-registerAADApp.sh.

**Comment by danielkon96** [comment]
Thanks for the report. Do you have anymore logged output? The script calls `azad app create --display-name $AD_APP_NAME --homepage $HOMEPAGE --reply-urls $REPLY_URLS --required-resource-accesses @./TemplateFiles/manifest.json -o json | jq -r '.appId'` this command and something went wrong. I was wondering if you got another error before the output you posted.

**Comment by Whowong** [comment]
Ah yes there is...  Here it is:

****BEGIN @ 22:16:53: Call ADD App Creation script****
BEGIN @ 22:16:53: Register AAD Application...
WARNING: Found an existing application instance of "0199ed5e-5978-4331-b941-48b37cd2e951". We will patch it
ERROR: Insufficient privileges to complete the operation.
CLIENT_ID:
Polling status of AAD object creation for app....
ERROR: argument --id: expected one argument

It looks like someone else has already created the App Registration which is why I cant modify it.

**Comment by danielkon96** [comment]
Thanks for the feedback. We will make it more clear that a unique name must be used. Thanks!

**Comment by danielkon96** [comment]
Issue #73 addresses this issue. Closing.
