### ISSUE TITLE
Update deprecated documentation

### ISSUE THREAD

**Issue by kevinmgates** [Azure/EasyAuthForK8s#9]
Edit (by Danielkon96): [https://github.com/Azure/EasyAuthForK8s/blob/master/docs/setup-instructions.md](https://github.com/Azure/EasyAuthForK8s/blob/master/docs/setup-instructions.md) is currently outdated with deprecation errors.

**Comment by danielkon96** [comment]
[https://github.com/Azure/EasyAuthForK8s/blob/master/docs/setup-instructions.md](https://github.com/Azure/EasyAuthForK8s/blob/master/docs/setup-instructions.md) is currently outdated with deprecation errors.
